name: api_uas
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.6
  video_player: ^2.6.4  # Menambahkan video_player untuk live background

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bg.png  # Background gambar (jika ada)
    - assets/background.mp4  # Video untuk live background

